AWSTemplateFormatVersion: "2010-09-09"
Description: Sysdig for Cloud - AWS Edition

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings"
        Parameters:
          - SysdigSecureEndpoint
          - SysdigSecureAPIToken

      - Label:
          default: "Modules to Deploy"
        Parameters:
          - CloudBenchDeploy
          - CloudConnectorDeploy
          - ECRImageScanningDeploy
          - ECSImageScanningDeploy

      - Label:
          default: "Existing Infrastructure"
        Parameters:
          - ExistentECSCluster
          - ExistentECSClusterVPC
          - ExistentECSClusterPrivateSubnets
          - ExistentCloudTrailSNSTopic

    ParameterLabels:
      SysdigSecureEndpoint:
        default: "Sysdig Secure Endpoint"
      SysdigSecureAPIToken:
        default: "Sysdig Secure API Token"
      CloudBenchDeploy:
        default: "Do you want to deploy Cloud Security Posture Management / Compliance?"
      CloudConnectorDeploy:
        default: "Do you want to deploy Real-Time Threat Investigation based on CloudTrail?"
      ECRImageScanningDeploy:
        default: "Do you want to deploy ECR Image Registry Scanning?"
      ECSImageScanningDeploy:
        default: "Do you want to deploy Fargate Image Scanning?"
      ExistentECSCluster:
        default: "ECS Cluster Name"
      ExistentECSClusterVPC:
        default: "VPC Id"
      ExistentECSClusterPrivateSubnets:
        default: "Private subnet Id's"
      ExistentCloudTrailSNSTopic:
        default: "CloudTrail SNS Topic"

Parameters:
  CloudConnectorDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ECRImageScanningDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ECSImageScanningDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  CloudBenchDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ExistentECSCluster:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentECSClusterVPC:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentECSClusterPrivateSubnets:
    Type: List<String>
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentCloudTrailSNSTopic:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud

  SysdigSecureAPIToken:
    Type: String
    NoEcho: true
  SysdigSecureEndpoint:
    Type: String
    AllowedValues:
      - https://secure.sysdig.com
      - https://us2.app.sysdig.com
      - https://eu1.app.sysdig.com
    Default: https://secure.sysdig.com

Conditions:
  DeployCloudScanning: !Or
    - !Equals [!Ref ECRImageScanningDeploy, "Yes"]
    - !Equals [!Ref ECSImageScanningDeploy, "Yes"]

Resources:

  CloudTrailStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../cloudtrail/cloudtrail.yaml
      Parameters:
        NamingPrefix: !Join ['-', ['SysdigCloud', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
        ExistingCloudTrailSNSTopic: !Ref ExistentCloudTrailSNSTopic

  RolesAndPermissionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../cloudvision-childaccount/cloudvision-childaccount.yaml
      Parameters:
        NamingPrefix: !Join ['-', ['SysdigCloud', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
        MainAccountID: !Ref AWS::AccountId
        CloudConnectorDeploy: !Ref CloudConnectorDeploy
        CloudScanningDeploy: !If [DeployCloudScanning, "Yes", "No"]
        CloudBenchDeploy: !Ref CloudBenchDeploy

  CloudVisionComponentsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../cloudvision-mainaccount/cloudvision-mainaccount.yaml
      Parameters:
        NamingPrefix: !Join ['-', ['SysdigCloud', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
        AccountsAndRegionsList: !Sub "${AWS::AccountId}:${AWS::Region}"
        CloudConnectorDeploy: !Ref CloudConnectorDeploy
        ECRImageScanningDeploy: !Ref ECRImageScanningDeploy
        ECSImageScanningDeploy: !Ref ECSImageScanningDeploy
        CloudBenchDeploy: !Ref CloudBenchDeploy
        ExistentECSCluster: !Ref ExistentECSCluster
        ExistentECSClusterVPC: !Ref ExistentECSClusterVPC
        ExistentECSClusterPrivateSubnets: !Join [",", !Ref ExistentECSClusterPrivateSubnets]
        SysdigSecureAPIToken: !Ref SysdigSecureAPIToken
        SysdigSecureEndpoint: !Ref SysdigSecureEndpoint
