AWSTemplateFormatVersion: "2010-09-09"
Description: Sysdig for Cloud - Deployment in AWS Organization main account

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Sysdig Settings"
        Parameters:
          - SysdigSecureEndpoint
          - SysdigSecureAPIToken

      - Label:
          default: "Modules to Deploy"
        Parameters:
          - CloudBenchDeploy
          - CloudConnectorDeploy
          - ECRImageScanningDeploy
          - ECSImageScanningDeploy

      - Label:
          default: "Organization CloudTrail"
        Parameters:
          - ExistentCloudTrailSNSTopic

      - Label:
          default: Children accounts
        Parameters:
          - NamingPrefix
          - BenchAccountsList

      - Label:
          default: "Existing Infrastructure"
        Parameters:
          - ExistentECSCluster
          - ExistentECSClusterVPC
          - ExistentECSClusterPrivateSubnets

    ParameterLabels:
      NamingPrefix:
        default: Resource naming convention - prefix
      BenchAccountsList:
        default: Benchmarking child AWS accounts
      SysdigSecureEndpoint:
        default: "Sysdig Secure Endpoint"
      SysdigSecureAPIToken:
        default: "Sysdig Secure API Token"
      CloudBenchDeploy:
        default: "Do you want to deploy Cloud Security Posture Management / Compliance?"
      CloudConnectorDeploy:
        default: "Do you want to deploy Real-Time Threat Investigation based on CloudTrail?"
      ECRImageScanningDeploy:
        default: "Do you want to deploy ECR Image Registry Scanning?"
      ECSImageScanningDeploy:
        default: "Do you want to deploy Fargate Image Scanning?"
      ExistentECSCluster:
        default: "ECS Cluster Name"
      ExistentECSClusterVPC:
        default: "VPC Id"
      ExistentECSClusterPrivateSubnets:
        default: "Private subnet Id's"
      ExistentCloudTrailSNSTopic:
        default: "Organization CloudTrail SNS Topic."

Parameters:
  NamingPrefix:
    Type: String
    Default: "SysdigCloud"
    Description: Prefix for resource names. Use the default unless you need to install multiple instances, and modify the deployment at the main account accordingly
    MinLength: 1
    MaxLength: 64
    AllowedPattern : "^[a-zA-Z0-9\\-]+$"
    ConstraintDescription: Must enter a naming prefix up to 64 alphanumeric characters

  BenchAccountsList:
    Type: CommaDelimitedList
    Default: ""
    Description: "A comma separated list of child AWS accounts where benchmarks will run. Format: account1,account2,..."

  CloudConnectorDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ECRImageScanningDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ECSImageScanningDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  CloudBenchDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  ExistentECSCluster:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentECSClusterVPC:
    Type: String
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentECSClusterPrivateSubnets:
    Type: List<String>
    Default: ""
    Description: Leave it blank to let us to deploy the infrastructure required for running Sysdig for Cloud
  ExistentCloudTrailSNSTopic:
    Type: String
    Description: Provide the ARN of the SNS topic where Organization CloudTrail publishes notifications. It must be in the current region.

  SysdigSecureAPIToken:
    Type: String
    NoEcho: true
  SysdigSecureEndpoint:
    Type: String
    AllowedValues:
      - https://secure.sysdig.com
      - https://us2.app.sysdig.com
      - https://eu1.app.sysdig.com
    Default: https://secure.sysdig.com

Resources:

  CloudVisionTrail:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../cloudtrail/cloudtrail.yaml
      Parameters:
        NamingPrefix: !Ref NamingPrefix
        ExistingCloudTrailSNSTopic: !Ref ExistentCloudTrailSNSTopic

  CloudVisionComponents:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../cloudvision-mainaccount/cloudvision-mainaccount.yaml
      Parameters:
        NamingPrefix: !Ref NamingPrefix
        TrailAccountsAndRegionsList: !Sub "${AWS::AccountId}:${AWS::Region}"
        BenchAccountsList: !Join [",", !Ref BenchAccountsList]
        CloudConnectorDeploy: !Ref CloudConnectorDeploy
        ECRImageScanningDeploy: !Ref ECRImageScanningDeploy
        ECSImageScanningDeploy: !Ref ECSImageScanningDeploy
        CloudBenchDeploy: !Ref CloudBenchDeploy
        ExistentECSCluster: !Ref ExistentECSCluster
        ExistentECSClusterVPC: !Ref ExistentECSClusterVPC
        ExistentECSClusterPrivateSubnets: !Join [",", !Ref ExistentECSClusterPrivateSubnets]
        SysdigSecureAPIToken: !Ref SysdigSecureAPIToken
        SysdigSecureEndpoint: !Ref SysdigSecureEndpoint
