AWSTemplateFormatVersion: "2010-09-09"
Description: Sysdig CloudVision for AWS

Resources:
  ECSFargateClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../ECSFargateCluster/ECSFargateCluster.yaml
