AWSTemplateFormatVersion: "2010-09-09"
Description: Sysdig CloudVision for AWS

Parameters:
  SysdigSecureAPIToken:
    Type: String
    Description: "Enter your Sysdig Secure API Token"
    NoEcho: true
  SysdigSecureEndpoint:
    Type: String
    Description: "Enter your Sysdig Secure Endpoint"
    Default: "https://secure.sysdig.com"

  ECRImageScanningDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Description: >
      Choose if you want to deploy the ECR Repository Image Scanning feature
    Default: "Yes"

  ECRImageScanningMode:
    Type: String
    AllowedValues:
      - "Inline"
      - "Backend"
    Description: >
      Choose how the scan will be performed. If choose Inline it will use AWS
      infrastructure and don't need outside access, this option makes scan
      faster. If choose Backend it will be done on Sysdig's infrastructure.
    Default: "Inline"

  CloudConnectorDeploy:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Description: >
      Choose if you want to deploy the CloudConnector for CloudTrail
    Default: "Yes"

  ECSCluster:
    Type: String
    Description: ECS Fargate Cluster where deploy the CloudVision workload
    Default: ""
  ECSClusterVPC:
    Type: String
    Description: VPC where the CloudVision workload will be deployed
    Default: ""
  ECSClusterPublicSubnets:
    Type: List<String>
    Description: Public Subnets where the CloudVision LoadBalancers will be deployed
    Default: ""
  ECSClusterPrivateSubnets:
    Type: List<String>
    Description: Private Subnets where the CloudVision workload will be deployed
    Default: ""

Conditions:
  DeployECRImageScanning: !Equals [!Ref ECRImageScanningDeploy, "Yes"]
  DeployECRInlineImageScanning: !And
    - !Condition DeployECRImageScanning
    - !Equals [!Ref "ECRImageScanningMode", "Inline"]
  DeployCloudConnector: !Equals [!Ref CloudConnectorDeploy, "Yes"]
  RequiresNewECSCluster:
    Fn::Or:
      - Fn::Equals:
        - !Ref ECSCluster
        - ""
      - Fn::Equals:
        - !Ref ECSClusterVPC
        - ""
      - Fn::Equals:
        - !Join [",", !Ref ECSClusterPublicSubnets]
        - ""
      - Fn::Equals:
        - !Join [",", !Ref ECSClusterPrivateSubnets]
        - ""
  DeployNewECSCluster: !And
       - !Condition DeployCloudConnector
       - !Condition RequiresNewECSCluster

Resources:
  ECRInlineImageScanningStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployECRInlineImageScanning
    Properties:
      TemplateURL: ../ECRImageScanning/Inline/Inline.yaml
      Parameters:
        SysdigSecureAPIToken: !Ref SysdigSecureAPIToken
        SysdigSecureEndpoint: !Ref SysdigSecureEndpoint

  ECSFargateClusterStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployNewECSCluster
    Properties:
      TemplateURL: ../ECSFargateCluster/ECSFargateCluster.yaml

  CloudConnectorStack:
    Type: AWS::CloudFormation::Stack
    Condition: DeployCloudConnector
    Properties:
      TemplateURL: ../CloudConnector/CloudConnector.yaml
      Parameters:
        ECSCluster: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.ClusterName"], !Ref ECSCluster ]
        VPC: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.VPC"], !Ref ECSClusterVPC ]
        PublicSubnets: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.PublicSubnets"], !Ref ECSClusterPublicSubnets ]
        PrivateSubnets: !If [ DeployNewECSCluster, !GetAtt ["ECSFargateClusterStack", "Outputs.PrivateSubnets"], !Ref ECSClusterPrivateSubnets ]
