AWSTemplateFormatVersion: "2010-09-09"
Description: Fargate Cluster where Sysdig CloudVision apps are deployed

Parameters:
  NamingPrefix:
    Type: String
    Default: "SysdigCloud"
    Description: Prefix for resource names. Use the default unless you need to install multiple instances, and modify the deployment at the main account accordingly
    MinLength: 1
    MaxLength: 64
    AllowedPattern : "^[a-zA-Z0-9\\-]+$"
    ConstraintDescription: Must enter a naming prefix up to 64 alphanumeric characters

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecsfargatecluster-vpc.yaml

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${NamingPrefix}-ECSCluster"

Outputs:
  ClusterName:
    Description: Cluster name for Sysdig CloudVision workload
    Value: !Ref ECSCluster

  VPC:
    Description: The VPC ID
    Value: !GetAtt ["VPC", "Outputs.VPC"]

  PublicSubnets:
    Description: Public Subnets
    Value: !GetAtt ["VPC", "Outputs.PublicSubnets"]

  PrivateSubnets:
    Description: Private Subnets
    Value: !GetAtt ["VPC", "Outputs.PrivateSubnets"]
